// Bsa2023CertificateService — generates BSA 2023 Section 63 Part A certificates.
//
// The Bharatiya Sakshya Adhiniyam, 2023 (BSA) Section 63 governs the
// admissibility of electronic records as evidence in Indian courts.
// It requires a certificate from a person occupying a responsible position
// in relation to the operation of the device or the management of relevant
// activities.
//
// Part A (auto-generated by this service):
//   A machine-produced record containing all the data and metadata required
//   by BSA Section 63(2), including:
//     (a) Identification of the electronic record
//     (b) Description of the device that produced it
//     (c) Conditions relating to the device's proper functioning
//     (d) Applicable safeguards (cryptographic integrity, access controls)
//
// Part B (human workflow — separate feature):
//   A declaration signed by a forensic expert or authorized officer,
//   stating that the conditions of Section 63 are satisfied.
//
// The Part A certificate is a structured data object. The audit portal
// renders it as printable HTML (browser Print → PDF).
// A court never sees raw JSON — they see the formatted certificate.

import type { VerificationResult } from './ForensicVerifier'
import { createServiceLogger } from '../logger'

const log = createServiceLogger('Bsa2023CertificateService')

// ── Certificate data structure ───────────────────────────────────────────────

export interface Bsa2023PartACertificate {
  // Certificate metadata
  certificateId:     string    // Unique reference for this certificate
  generatedAtUtc:    string    // ISO 8601
  platformVersion:   string    // JADS version
  certificateType:   'BSA_2023_SECTION_63_PART_A'

  // Section 63(2)(a) — Identification of the electronic record
  electronicRecord: {
    missionId:           string
    databaseRecordId:    string
    missionStartUtc:     string
    missionEndUtc:       string
    recordCount:         number
    operatorId:          string
    deviceId:            string
    deviceModel:         string | null
    droneManufacturer:   string | null
    droneSerialNumber:   string | null
    uinNumber:           string | null
    npntClassification:  string
  }

  // Section 63(2)(b) — Description of the device that produced it
  deviceDescription: {
    deviceType:          string    // "Android mobile device"
    operatingSystem:     string | null
    cryptographicModule: string    // "ECDSA P-256 (RFC 6979) + ML-DSA-65 (FIPS 204)"
    keyStorage:          string    // StrongBox/Software/Unknown
    secureBoot:          string    // Verified/Not Verified/Unknown
    hashChainAlgorithm:  string    // "SHA-256"
    canonicalPayloadSize: string   // "96 bytes"
    signatureAlgorithm:  string    // "ECDSA P-256 with SHA-256 (DER-encoded)"
  }

  // Section 63(2)(c) — Conditions relating to the device
  operatingConditions: {
    ntpSyncStatus:       string
    ntpOffsetMs:         number | null
    timeSynchronisation: string    // Human-readable summary
    gnssIntegritySummary: string
    chainIntegritySummary: string
  }

  // Section 63(2)(d) — Applicable safeguards
  safeguards: {
    hashChainIntegrity:     string
    ecdsaSignatureStatus:   string
    pqcSignatureStatus:     string
    duplicateCheckStatus:   string
    zoneComplianceStatus:   string
    crlArchiveStatus:       string
    hardwareSecurityStatus: string
    timestampMonotonicity:  string
    databaseImmutability:   string    // PostgreSQL audit triggers
    externalAnchoring:      string    // Merkle root anchoring
  }

  // Forensic verification summary
  forensicVerification: {
    verifiedAtUtc:           string
    complianceTimeAnchor:    string
    allInvariantsHold:       boolean
    invariantSummary:        Array<{
      code:     string
      label:    string
      pass:     boolean
      critical: boolean
      detail:   string
    }>
    failureCount:            number
    violationCount:          number
  }

  // Compliance anchoring
  complianceAnchoring: {
    complianceTimeAnchor:    string    // = missionEndUtcMs (frozen at landing)
    anchorExplanation:       string
  }

  // Legal notice
  legalNotice: {
    statute:           string
    section:           string
    partDescription:   string
    disclaimer:        string
    partBRequirement:  string
  }
}

// ── Service ──────────────────────────────────────────────────────────────────

export class Bsa2023CertificateService {

  generatePartA(
    mission: Record<string, any>,
    verification: VerificationResult,
  ): Bsa2023PartACertificate {
    const now = new Date().toISOString()
    const certId = `BSA63-${mission.missionId}-${Date.now().toString(36).toUpperCase()}`

    log.info('bsa2023_part_a_generated', { data: {
      missionId: mission.missionId,
      certificateId: certId,
      allInvariantsHold: verification.allInvariantsHold,
    }})

    return {
      certificateId:   certId,
      generatedAtUtc:  now,
      platformVersion: '4.0',
      certificateType: 'BSA_2023_SECTION_63_PART_A',

      electronicRecord: {
        missionId:          mission.missionId,
        databaseRecordId:   mission.id,
        missionStartUtc:    new Date(Number(mission.missionStartUtcMs)).toISOString(),
        missionEndUtc:      mission.missionEndUtcMs
          ? new Date(Number(mission.missionEndUtcMs)).toISOString()
          : 'Mission not yet ended',
        recordCount:        verification.recordCount,
        operatorId:         mission.operatorId,
        deviceId:           mission.deviceId,
        deviceModel:        mission.deviceModel ?? null,
        droneManufacturer:  mission.droneManufacturer ?? null,
        droneSerialNumber:  mission.droneSerialNumber ?? null,
        uinNumber:          mission.uinNumber ?? null,
        npntClassification: mission.npntClassification ?? 'UNKNOWN',
      },

      deviceDescription: {
        deviceType:          'Android mobile device with JADS telemetry engine',
        operatingSystem:     mission.androidVersionAtUpload
          ? `Android ${mission.androidVersionAtUpload}`
          : null,
        cryptographicModule: 'ECDSA P-256 (RFC 6979) + ML-DSA-65 (NIST FIPS 204)',
        keyStorage:          mission.strongboxBacked === true
          ? 'Android Keystore with StrongBox hardware backing (tamper-resistant)'
          : mission.strongboxBacked === false
            ? 'Android Keystore (software-only — no hardware security module)'
            : 'Unknown — device attestation not provided',
        secureBoot:          mission.secureBootVerified === true
          ? 'Verified — device secure boot chain intact'
          : mission.secureBootVerified === false
            ? 'Not verified — secure boot status negative'
            : 'Unknown — secure boot status not reported',
        hashChainAlgorithm:  'SHA-256 (NIST FIPS 180-4)',
        canonicalPayloadSize: '96 bytes per telemetry record',
        signatureAlgorithm:  'ECDSA P-256 with SHA-256, DER-encoded (RFC 6979)',
      },

      operatingConditions: {
        ntpSyncStatus:       mission.ntpSyncStatus ?? 'UNKNOWN',
        ntpOffsetMs:         mission.ntpOffsetMs ?? null,
        timeSynchronisation: this.describeTimeSyncCondition(
          mission.ntpSyncStatus, mission.ntpOffsetMs
        ),
        gnssIntegritySummary: this.describeGnssCondition(verification),
        chainIntegritySummary: this.describeChainCondition(verification),
      },

      safeguards: {
        hashChainIntegrity:     this.getInvariantStatus(verification, 'I1_HASH_CHAIN'),
        ecdsaSignatureStatus:   this.getInvariantStatus(verification, 'I1_HASH_CHAIN'),
        pqcSignatureStatus:     this.getInvariantStatus(verification, 'I10_PQC_HYBRID'),
        duplicateCheckStatus:   this.getInvariantStatus(verification, 'I5_NO_DUPLICATE'),
        zoneComplianceStatus:   this.getInvariantStatus(verification, 'I6_ZONE_COMPLIANCE'),
        crlArchiveStatus:       this.getInvariantStatus(verification, 'I4_CRL_ARCHIVED'),
        hardwareSecurityStatus: this.getInvariantStatus(verification, 'I8_HARDWARE_SECURITY'),
        timestampMonotonicity:  this.getInvariantStatus(verification, 'I9_TIMESTAMP_MONOTONIC'),
        databaseImmutability:   'PostgreSQL audit triggers enforce append-only audit log (no UPDATE/DELETE)',
        externalAnchoring:      'Daily Merkle root anchoring to external trust backends',
      },

      forensicVerification: {
        verifiedAtUtc:        verification.verifiedAt,
        complianceTimeAnchor: verification.complianceTimeAnchor,
        allInvariantsHold:    verification.allInvariantsHold,
        invariantSummary:     verification.invariants.map(i => ({
          code:     i.code,
          label:    i.label,
          pass:     i.pass,
          critical: i.critical,
          detail:   i.detail,
        })),
        failureCount:         verification.failureDetails.length,
        violationCount:       verification.violationCount,
      },

      complianceAnchoring: {
        complianceTimeAnchor: verification.complianceTimeAnchor,
        anchorExplanation:
          'The compliance time anchor is frozen at the moment the drone landed ' +
          '(missionEndUtcMs). It is never recalculated, never updated, and never ' +
          'uses the current system time. All forensic checks are evaluated against ' +
          'this frozen timestamp. This ensures temporal consistency for legal proceedings.',
      },

      legalNotice: {
        statute:          'Bharatiya Sakshya Adhiniyam, 2023 (BSA)',
        section:          'Section 63 — Admissibility of electronic records',
        partDescription:  'Part A — System-generated certificate containing identification, ' +
                          'device description, operating conditions, and applicable safeguards ' +
                          'as required by Section 63(2)(a) through 63(2)(d).',
        disclaimer:
          'This Part A certificate is automatically generated by the JADS platform. ' +
          'It documents the technical conditions and safeguards applicable to the ' +
          'electronic record at the time of generation. This certificate alone does ' +
          'not satisfy the requirements of BSA Section 63 — a Part B declaration ' +
          'signed by an authorised officer is also required.',
        partBRequirement:
          'For this electronic record to be admissible under BSA Section 63, a person ' +
          'occupying a responsible official position in relation to the operation of ' +
          'the relevant device or the management of relevant activities must sign a ' +
          'Part B declaration affirming that the conditions of Section 63 are satisfied.',
      },
    }
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  private describeTimeSyncCondition(ntpStatus: string | null, offsetMs: number | null): string {
    if (!ntpStatus || ntpStatus === 'UNKNOWN') {
      return 'NTP synchronisation status was not recorded for this mission.'
    }
    if (ntpStatus === 'SYNCED') {
      return offsetMs != null
        ? `Device clock was synchronised via NTP quorum (3-server voting). ` +
          `Clock offset at mission time: ${offsetMs}ms.`
        : `Device clock was synchronised via NTP quorum. Offset not recorded.`
    }
    if (ntpStatus === 'DEGRADED') {
      return `NTP synchronisation was degraded. ` +
        `Clock offset at mission time: ${offsetMs ?? 'unknown'}ms. ` +
        `Timestamps may be less accurate but are not rejected.`
    }
    return `NTP synchronisation FAILED — timestamps are not independently anchored. ` +
      `This may affect the evidentiary weight of temporal claims.`
  }

  private describeGnssCondition(verification: VerificationResult): string {
    const i7 = verification.invariants.find(i => i.code === 'I7_GNSS_INTEGRITY')
    return i7 ? i7.detail : 'GNSS integrity data not available.'
  }

  private describeChainCondition(verification: VerificationResult): string {
    const i1 = verification.invariants.find(i => i.code === 'I1_HASH_CHAIN')
    return i1 ? i1.detail : 'Hash chain integrity data not available.'
  }

  private getInvariantStatus(verification: VerificationResult, code: string): string {
    const inv = verification.invariants.find(i => i.code === code)
    if (!inv) return 'Not evaluated'
    return inv.pass ? `PASS — ${inv.detail}` : `FAIL — ${inv.detail}`
  }
}
